[3.18] Build python-pytz against Python 3.9 on el8/9
theforeman/pulpcore-packaging pull request #438
Opened 2022-04-07 18:10 UTC by dsavineau

el7 isn't a target anymore so we don't need the SCL configuration.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

2022-04-12 19:55 UTC, zjhuntin commented
[test rpm]

2022-04-19 08:09 UTC, evgeni commented
[test rpm]

2022-04-19 08:19 UTC, evgeni requested changes
The diff looks sane if we say "we don't need SCLs anymore". However, in reality, we still have other branches that *do* need EL7/SCL to work. Dropping the SCL macro usage here means that we cannot easily backport changes done in the `3.18` branch to `3.17` and older.

If we don't drop them just yet, the EL8/EL9 builds will remain SCL-less (as the macros are undef there) but we'll be able to share changes with older branches, which I think is a great benefit.

So this PR should be really just a changelog entry and an increase of `%release`.

2022-04-26 22:06 UTC, Spredzy commented
This PR can be closed @Odilhao as we have been doing the work in other PRs

2022-04-27 09:36 UTC, closed without merging