Build python-solv
theforeman/pulpcore-packaging pull request #938
Opened 2024-04-15 14:44 UTC by pcreech

2024-04-16 09:57 UTC, ekohl requested changes

2024-04-16 09:57 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}/usr/bin/
This duplicates line 123

2024-04-16 09:57 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +  -DPYTHON_INCLUDE_DIR=/usr/include/python3.11            \
```suggestion
  -DPYTHON_LIBRARY=/usr/lib64/libpython%{python_pkgversion}.so.1.0        \
  -DPYTHON_INCLUDE_DIR=/usr/include/python%{python_pkgversion}            \
```

2024-04-16 09:57 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}/usr/include/
Should this use RPM macros instead of hardcoding paths?
```suggestion
rm -rf %{buildroot}%{_bindir}
rm -rf %{buildroot}%{_includedir}
```

2024-04-17 09:42 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm %{buildroot}/usr/lib64/pkgconfig/libsolv*.pc
```suggestion
rm %{buildroot}%{_libdir}/libsolv*.a
rm %{buildroot}%{_libdir}/pkgconfig/libsolv*.pc
```

2024-04-17 09:46 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}/usr/bin/
I wonder what's "cleaner", `rm -rf` in `%install` or marking all those paths as `%exclude` in `%files`.
Both ways work and I'd not block on that, but wanted to raise the thought :)

2024-04-24 06:55 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}/usr/bin/
```suggestion
```

2024-04-24 07:00 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +  -DPYTHON_INCLUDE_DIR=/usr/include/python%{python_pkgversion}            \
```suggestion
  -DPYTHON_LIBRARY=/usr/lib64/libpython%{python3_pkgversion}.so.1.0        \
  -DPYTHON_INCLUDE_DIR=/usr/include/python%{python3_pkgversion}            \
```

2024-04-24 07:10 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}%{_libdir}/debug/
```suggestion
```

I couldn't find anything installed there

2024-04-24 07:11 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}%{_includedir}
```suggestion
rm -rf %{buildroot}%{_includedir}/solv/
```

2024-04-24 07:13 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}%{_datadir}
```suggestion
rm %{buildroot}%{_mandir}/man*/*solv*
```

2024-04-24 07:21 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm %{buildroot}%{_mandir}/man*/*solv*
```suggestion
rm %{buildroot}%{_mandir}/man*/*solv*
rm %{buildroot}%{_mandir}/man1/installcheck.1*
rm %{buildroot}%{_datadir}/cmake/Modules/FindLibSolv.cmake
```

2024-04-24 07:24 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +rm -rf %{buildroot}%{_bindir}
```suggestion
rm %{buildroot}%{_bindir}/*solv
rm %{buildroot}%{_bindir}/installcheck
```

2024-04-24 08:01 UTC, evgeni commented
@ekohl @pcreech sorry for the small flood in your inbox, but I wanted to get this moving further.
The final version does two things:
- "apply suggestions" -- this uses macros as suggested by Ewoud and also tightens the `rm` to real paths, so that we don't delete something that we didn't want to delete.
- "move things to %exclude" -- well, converts `rm` to `%exclude` which I personally find cleaner, but feel free to disagree :)

With those applied, this builds a nice `python3.11-solv` pkg with no dependency on `libsolv`:

```
# rpm -q --requires python3.11-solv
libbz2.so.1()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.28)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.33)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
liblzma.so.5()(64bit)
liblzma.so.5(XZ_5.0)(64bit)
librpm.so.9()(64bit)
librpmio.so.9()(64bit)
libxml2.so.2()(64bit)
libxml2.so.2(LIBXML2_2.4.30)(64bit)
libxml2.so.2(LIBXML2_2.6.0)(64bit)
libz.so.1()(64bit)
libz.so.1(ZLIB_1.2.3.3)(64bit)
libzstd.so.1()(64bit)
python(abi) = 3.11
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rtld(GNU_HASH)
```

`import solv` works on an EL9 python 3.11 install.

one downside of the `%exclude` approach: it seems to still include `build-id`s for the excluded binaries:

```console
# rpm -q -l python3.11-solv |grep build-id.... | xargs file
/usr/lib/.build-id/07/c76a2e53a55ced39bf94546afd9eb666c4e1be: broken symbolic link to ../../../../usr/bin/comps2solv
/usr/lib/.build-id/0e/1e52d684343ce26182b105333a4d7d4bfa79bd: broken symbolic link to ../../../../usr/bin/dumpsolv
/usr/lib/.build-id/14/df527444f580b482468fed84c1cf733388dc3a: broken symbolic link to ../../../../usr/bin/updateinfoxml2solv
/usr/lib/.build-id/1a/85b8cab1593544b3d1cb4d6768373df573f41c: broken symbolic link to ../../../../usr/bin/installcheck
/usr/lib/.build-id/1f/dc6b64893c2593925d880eb601aa0b74a25df7: broken symbolic link to ../../../../usr/bin/solv
/usr/lib/.build-id/27/b9e9e6c68167d466dab23794b7ecdd0830d170: symbolic link to ../../../../usr/lib64/python3.11/site-packages/_solv.so
/usr/lib/.build-id/29/6bd823b03ff93025c56765cd04faa8213ef8de: broken symbolic link to ../../../../usr/bin/rpmmd2solv
/usr/lib/.build-id/31/c427f7c5b6463a82962707ad5e2620cca37084: broken symbolic link to ../../../../usr/bin/susetags2solv
/usr/lib/.build-id/3c/062d6bfa147cccc72bae887abbab58d605886e: broken symbolic link to ../../../../usr/bin/deb2solv
/usr/lib/.build-id/3d/1b077772c79a263edf2774ab761770043fcf1d: broken symbolic link to ../../../../usr/bin/rpms2solv
/usr/lib/.build-id/4a/6fb6db2787d589fdefae358ef9bed31e561dff: broken symbolic link to ../../../../usr/bin/rpmdb2solv
/usr/lib/.build-id/56/ffabdedbcf1d2184b8876b6d28977b1707ce46: broken symbolic link to ../../../../usr/bin/mergesolv
/usr/lib/.build-id/5c/634856a0b90f41ebc51f8448f7261df77fe2be: broken symbolic link to ../../../../usr/bin/testsolv
/usr/lib/.build-id/64/220783ba487297eeea22ef39b15b9ba88d27b8: broken symbolic link to ../../../../usr/bin/repomdxml2solv
/usr/lib/.build-id/7b/f5478e770dcaabf53eed8511d103bc1af6b2c5: broken symbolic link to ../../../../usr/bin/helix2solv
/usr/lib/.build-id/93/0315309a708c9b2c1cf691b8bfff27f6d137e0: broken symbolic link to ../../../../usr/bin/archpkgs2solv
/usr/lib/.build-id/ac/a38c397d6b774fb227ed5394df33f1a1632bfa: broken symbolic link to ../../../../usr/bin/repo2solv
/usr/lib/.build-id/de/87b4d63e73dbc3a40302b8466f2ece549ba8a1: broken symbolic link to ../../../../usr/bin/deltainfoxml2solv
/usr/lib/.build-id/ec/672ddf29f8d22b8c2e551c93af3c79cfb8c4bf: broken symbolic link to ../../../../usr/bin/conda2solv
/usr/lib/.build-id/f0/75865dc02f9081028ae1fa6b02692d54a4ef7c: broken symbolic link to ../../../../usr/bin/archrepo2solv
/usr/lib/.build-id/f5/f8a762d6904c2d7a53ab443378610c660b8944: broken symbolic link to ../../../../usr/bin/appdata2solv
```

2024-04-24 08:40 UTC, evgeni commented
I have opened https://bugzilla.redhat.com/show_bug.cgi?id=2276846

2024-04-24 08:44 UTC, evgeni commented
https://github.com/rpm-software-management/rpm/issues/1094 says this is "as it should be", so I am reverting to the `rm` method.

2024-04-24 08:48 UTC, evgeni approved these changes

2024-04-25 10:48 UTC, ekohl reviewed
The end result looks ok, but some more macros should be used.

2024-04-25 10:48 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +  -DPYTHON_LIBRARY=/usr/lib64/libpython%{python3_pkgversion}.so.1.0        \
```suggestion
  -DPYTHON_LIBRARY=%{_libdir}/libpython%{python3_pkgversion}.so.1.0        \
```

2024-04-25 10:48 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +  -DPYTHON_INCLUDE_DIR=/usr/include/python%{python3_pkgversion}            \
```suggestion
  -DPYTHON_INCLUDE_DIR=%{_includedir}/python%{python3_pkgversion}            \
```

2024-04-25 10:48 UTC, ekohl commented on packages/python-solv/python-solv.spec
> +%{python3_sitearch}/__pycache__/%{libname}.*
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_files_to_include suggests this:
```suggestion
%pycached %{python3_sitelib}/%{libname}.py
```

Not 100% sure that also works on EL8.

2024-04-25 11:02 UTC, evgeni commented on packages/python-solv/python-solv.spec
> +%{python3_sitearch}/__pycache__/%{libname}.*
It seems so, but we're not using this anywhere in our packaging, and I feel like solv is the wrong package to start experimenting ;)

2024-04-25 11:14 UTC, ekohl approved these changes

2024-04-25 15:52 UTC, merged